import type { LocalizedText } from "@/lib/course-data";

const text = (en: string, fr: string): LocalizedText => ({ en, fr });

export type MockExamMode = "foundation" | "practitioner" | "timed" | "weak-areas" | "bilingual";
export type MockExamTopic =
  | "fundamentals"
  | "isms"
  | "clauses"
  | "annex-a"
  | "risk"
  | "soa"
  | "audit"
  | "evidence"
  | "nonconformity"
  | "compare"
  | "implementation"
  | "terminology";

export type MockExamDifficulty = "easy" | "medium" | "hard";
export type MockExamQuestionType = "single-choice" | "multiple-select" | "true-false";

export type MockExamQuestion = {
  id: string;
  type: MockExamQuestionType;
  topic: MockExamTopic;
  difficulty: MockExamDifficulty;
  modes: MockExamMode[];
  prompt: LocalizedText;
  scenario?: LocalizedText;
  options: Array<{
    id: string;
    label: LocalizedText;
    rationale?: LocalizedText;
  }>;
  correctOptionIds: string[];
  explanation: LocalizedText;
  takeaway: LocalizedText;
  references: LocalizedText[];
};

export type MockExamDefinition = {
  id: MockExamMode;
  title: LocalizedText;
  description: LocalizedText;
  minutes: number;
  questionCount: number;
  accent: string;
  topics: MockExamTopic[];
};

const single = (
  id: string,
  topic: MockExamTopic,
  difficulty: MockExamDifficulty,
  modes: MockExamMode[],
  promptEn: string,
  promptFr: string,
  options: Array<{ id: string; en: string; fr: string }>,
  correctOptionId: string,
  explanationEn: string,
  explanationFr: string,
  takeawayEn: string,
  takeawayFr: string,
  references: Array<{ en: string; fr: string }>,
  scenario?: { en: string; fr: string },
): MockExamQuestion => ({
  id,
  type: "single-choice",
  topic,
  difficulty,
  modes,
  prompt: text(promptEn, promptFr),
  scenario: scenario ? text(scenario.en, scenario.fr) : undefined,
  options: options.map((option) => ({ id: option.id, label: text(option.en, option.fr) })),
  correctOptionIds: [correctOptionId],
  explanation: text(explanationEn, explanationFr),
  takeaway: text(takeawayEn, takeawayFr),
  references: references.map((reference) => text(reference.en, reference.fr)),
});

const multi = (
  id: string,
  topic: MockExamTopic,
  difficulty: MockExamDifficulty,
  modes: MockExamMode[],
  promptEn: string,
  promptFr: string,
  options: Array<{ id: string; en: string; fr: string }>,
  correctOptionIds: string[],
  explanationEn: string,
  explanationFr: string,
  takeawayEn: string,
  takeawayFr: string,
  references: Array<{ en: string; fr: string }>,
  scenario?: { en: string; fr: string },
): MockExamQuestion => ({
  id,
  type: "multiple-select",
  topic,
  difficulty,
  modes,
  prompt: text(promptEn, promptFr),
  scenario: scenario ? text(scenario.en, scenario.fr) : undefined,
  options: options.map((option) => ({ id: option.id, label: text(option.en, option.fr) })),
  correctOptionIds,
  explanation: text(explanationEn, explanationFr),
  takeaway: text(takeawayEn, takeawayFr),
  references: references.map((reference) => text(reference.en, reference.fr)),
});

const tf = (
  id: string,
  topic: MockExamTopic,
  difficulty: MockExamDifficulty,
  modes: MockExamMode[],
  promptEn: string,
  promptFr: string,
  correct: boolean,
  explanationEn: string,
  explanationFr: string,
  takeawayEn: string,
  takeawayFr: string,
  references: Array<{ en: string; fr: string }>,
  scenario?: { en: string; fr: string },
): MockExamQuestion => ({
  id,
  type: "true-false",
  topic,
  difficulty,
  modes,
  prompt: text(promptEn, promptFr),
  scenario: scenario ? text(scenario.en, scenario.fr) : undefined,
  options: [
    { id: "true", label: text("True", "Vrai") },
    { id: "false", label: text("False", "Faux") },
  ],
  correctOptionIds: [String(correct)],
  explanation: text(explanationEn, explanationFr),
  takeaway: text(takeawayEn, takeawayFr),
  references: references.map((reference) => text(reference.en, reference.fr)),
});

export const mockExamDefinitions: MockExamDefinition[] = [
  {
    id: "foundation",
    title: text("Foundation Exam", "Examen Fondamentaux"),
    description: text(
      "Core concepts, terminology, clauses 4 to 10, Annex A structure, and the logic of the ISMS.",
      "Concepts clés, terminologie, clauses 4 à 10, structure de l'Annexe A et logique du SMSI.",
    ),
    minutes: 25,
    questionCount: 16,
    accent: "from-sky-500/15 via-white to-indigo-500/10",
    topics: ["fundamentals", "isms", "clauses", "annex-a", "compare", "terminology"],
  },
  {
    id: "practitioner",
    title: text("Practitioner Exam", "Examen Praticien"),
    description: text(
      "Scenario-heavy exam focused on SoA decisions, evidence, risk treatment, audit reasoning, and business judgement.",
      "Examen orienté scénarios centré sur la SoA, la preuve, le traitement du risque, le raisonnement d'audit et le jugement métier.",
    ),
    minutes: 35,
    questionCount: 18,
    accent: "from-emerald-500/15 via-white to-cyan-500/10",
    topics: ["risk", "soa", "audit", "evidence", "nonconformity", "implementation"],
  },
  {
    id: "timed",
    title: text("Timed Mock Exam", "Examen Blanc Chronométré"),
    description: text(
      "A more realistic mixed assessment with a visible countdown and a professional exam flow.",
      "Une évaluation mixte plus réaliste avec compte à rebours visible et déroulé d'examen professionnel.",
    ),
    minutes: 40,
    questionCount: 24,
    accent: "from-rose-500/15 via-white to-amber-500/10",
    topics: ["fundamentals", "clauses", "annex-a", "risk", "soa", "audit", "evidence", "nonconformity", "compare", "implementation"],
  },
  {
    id: "weak-areas",
    title: text("Weak Areas Exam", "Examen Zones Faibles"),
    description: text(
      "Targets the domains where the learner has struggled most across prior practice and exam sessions.",
      "Cible les domaines où l'apprenant a le plus de difficultés dans ses sessions précédentes.",
    ),
    minutes: 20,
    questionCount: 12,
    accent: "from-amber-500/15 via-white to-orange-500/10",
    topics: ["clauses", "risk", "audit", "evidence", "nonconformity", "soa"],
  },
  {
    id: "bilingual",
    title: text("Bilingual Exam", "Examen Bilingue"),
    description: text(
      "Tests practical ISO 27001 understanding while reinforcing English/French working vocabulary.",
      "Teste la compréhension pratique de l'ISO 27001 tout en renforçant le vocabulaire de travail anglais/français.",
    ),
    minutes: 25,
    questionCount: 14,
    accent: "from-violet-500/15 via-white to-fuchsia-500/10",
    topics: ["terminology", "fundamentals", "soa", "audit", "compare"],
  },
];

export const mockExamTopicLabels: Record<MockExamTopic, LocalizedText> = {
  fundamentals: text("Fundamentals", "Fondamentaux"),
  isms: text("ISMS", "SMSI"),
  clauses: text("Clauses 4–10", "Clauses 4–10"),
  "annex-a": text("Annex A", "Annexe A"),
  risk: text("Risk", "Risque"),
  soa: text("Statement of Applicability", "Déclaration d'applicabilité"),
  audit: text("Audit", "Audit"),
  evidence: text("Evidence", "Preuve"),
  nonconformity: text("Nonconformity", "Non-conformité"),
  compare: text("Framework comparison", "Comparaison des référentiels"),
  implementation: text("Implementation journey", "Parcours de mise en oeuvre"),
  terminology: text("Bilingual terminology", "Terminologie bilingue"),
};

export const mockExamQuestions: MockExamQuestion[] = [
  single(
    "mx-001",
    "fundamentals",
    "easy",
    ["foundation", "timed", "bilingual"],
    "What is the main certifiable object in ISO/IEC 27001?",
    "Quel est l'objet principal certifiable dans l'ISO/IEC 27001 ?",
    [
      { id: "a", en: "The list of Annex A controls alone", fr: "La seule liste des mesures de l'Annexe A" },
      { id: "b", en: "The Information Security Management System", fr: "Le système de management de la sécurité de l'information" },
      { id: "c", en: "Only the internal audit procedure", fr: "Uniquement la procédure d'audit interne" },
      { id: "d", en: "Only the security policy", fr: "Uniquement la politique de sécurité" },
    ],
    "b",
    "The standard certifies the ISMS as a management system. Annex A controls support it, but certification is about the risk-based system working in context.",
    "La norme certifie le SMSI comme système de management. Les mesures de l'Annexe A le soutiennent, mais la certification vise le fonctionnement du système fondé sur le risque dans son contexte.",
    "Always explain ISO 27001 as a management system first, not as a checklist of controls.",
    "Expliquez toujours d'abord l'ISO 27001 comme un système de management, pas comme une checklist de mesures.",
    [{ en: "ISO 27001 fundamentals", fr: "Fondamentaux ISO 27001" }],
  ),
  single(
    "mx-002",
    "compare",
    "easy",
    ["foundation", "timed", "bilingual"],
    "Which statement best distinguishes ISO 27001 from ISO 27002?",
    "Quelle affirmation distingue le mieux l'ISO 27001 de l'ISO 27002 ?",
    [
      { id: "a", en: "ISO 27001 is guidance and ISO 27002 is certifiable", fr: "L'ISO 27001 est un guide et l'ISO 27002 est certifiable" },
      { id: "b", en: "ISO 27001 defines certifiable ISMS requirements and ISO 27002 gives implementation guidance", fr: "L'ISO 27001 définit des exigences certifiables du SMSI et l'ISO 27002 donne des conseils de mise en oeuvre" },
      { id: "c", en: "ISO 27002 is a law and ISO 27001 is a standard", fr: "L'ISO 27002 est une loi et l'ISO 27001 une norme" },
      { id: "d", en: "There is no meaningful difference", fr: "Il n'y a pas de différence significative" },
    ],
    "b",
    "ISO 27001 contains certifiable requirements. ISO 27002 helps interpret and implement controls but is not itself the certifiable standard.",
    "L'ISO 27001 contient les exigences certifiables. L'ISO 27002 aide à interpréter et mettre en oeuvre les mesures mais n'est pas elle-même la norme certifiable.",
    "Good exam and interview answers separate requirement, guidance, and law clearly.",
    "Les bonnes réponses d'examen et d'entretien distinguent clairement exigence, guide et loi.",
    [{ en: "ISO 27001 vs ISO 27002", fr: "ISO 27001 vs ISO 27002" }],
  ),
  tf(
    "mx-003",
    "annex-a",
    "easy",
    ["foundation", "timed"],
    "Annex A controls should be applied blindly because every certified company must implement all of them.",
    "Les mesures de l'Annexe A doivent être appliquées aveuglément car toute entreprise certifiée doit toutes les mettre en oeuvre.",
    false,
    "Controls are selected based on risk treatment, context, and applicability. The SoA explains what is applicable and why.",
    "Les mesures sont sélectionnées selon le traitement du risque, le contexte et l'applicabilité. La SoA explique ce qui est applicable et pourquoi.",
    "Risk-based selection is central to ISO 27001 credibility.",
    "La sélection fondée sur le risque est centrale pour la crédibilité de l'ISO 27001.",
    [{ en: "Annex A and SoA", fr: "Annexe A et SoA" }],
  ),
  single(
    "mx-004",
    "clauses",
    "medium",
    ["foundation", "timed", "weak-areas"],
    "Which clause is most directly associated with internal audits?",
    "Quelle clause est la plus directement associée aux audits internes ?",
    [
      { id: "a", en: "Clause 5 Leadership", fr: "Clause 5 Leadership" },
      { id: "b", en: "Clause 6 Planning", fr: "Clause 6 Planning" },
      { id: "c", en: "Clause 9 Performance evaluation", fr: "Clause 9 Évaluation des performances" },
      { id: "d", en: "Clause 10 Improvement", fr: "Clause 10 Amélioration" },
    ],
    "c",
    "Internal audits sit under performance evaluation because they are part of how the organization checks whether the ISMS is operating as intended.",
    "Les audits internes relèvent de l'évaluation des performances car ils font partie de la manière dont l'organisation vérifie que le SMSI fonctionne comme prévu.",
    "Link audit activity to checking effectiveness, not just to paperwork.",
    "Reliez l'activité d'audit à la vérification de l'efficacité, pas seulement à la paperasse.",
    [{ en: "Clause 9.2 Internal audit", fr: "Clause 9.2 Audit interne" }],
  ),
  single(
    "mx-005",
    "risk",
    "medium",
    ["foundation", "practitioner", "timed", "weak-areas"],
    "A company identifies a serious phishing risk affecting finance staff. What is the best ISO 27001-aligned next step?",
    "Une entreprise identifie un risque sérieux de phishing touchant les équipes finance. Quelle est la meilleure étape suivante alignée sur l'ISO 27001 ?",
    [
      { id: "a", en: "Purchase one new tool and mark the risk closed", fr: "Acheter un nouvel outil et marquer le risque comme clos" },
      { id: "b", en: "Assess treatment options, choose controls, assign owners, and retain evidence of the decision", fr: "Évaluer les options de traitement, choisir les mesures, désigner des responsables et conserver la preuve de la décision" },
      { id: "c", en: "Ignore the risk until the annual audit", fr: "Ignorer le risque jusqu'à l'audit annuel" },
      { id: "d", en: "Add every Annex A control to the SoA", fr: "Ajouter toutes les mesures de l'Annexe A à la SoA" },
    ],
    "b",
    "Risk treatment is a management decision process. The organization should assess treatment options, pick proportionate controls, assign ownership, and maintain traceability.",
    "Le traitement du risque est un processus de décision de management. L'organisation doit évaluer les options, choisir des mesures proportionnées, désigner les responsables et maintenir la traçabilité.",
    "The right answer usually combines judgement, ownership, and evidence.",
    "La bonne réponse combine généralement jugement, responsabilité et preuve.",
    [{ en: "Risk assessment and treatment", fr: "Analyse et traitement des risques" }],
  ),
  single(
    "mx-006",
    "soa",
    "medium",
    ["practitioner", "timed", "weak-areas", "bilingual"],
    "Which statement best reflects the role of the Statement of Applicability?",
    "Quelle affirmation reflète le mieux le rôle de la Déclaration d'applicabilité ?",
    [
      { id: "a", en: "It is a marketing brochure for customers", fr: "C'est une brochure marketing pour les clients" },
      { id: "b", en: "It maps applicable controls, exclusions, and implementation status to the organization’s risk treatment logic", fr: "Elle cartographie les mesures applicables, les exclusions et l'état de mise en oeuvre à la logique de traitement du risque de l'organisation" },
      { id: "c", en: "It replaces the risk register", fr: "Elle remplace le registre des risques" },
      { id: "d", en: "It is only used after certification", fr: "Elle n'est utilisée qu'après la certification" },
    ],
    "b",
    "The SoA is a core bridge between risk treatment decisions and Annex A control applicability, including justifications and implementation status.",
    "La SoA est un pont central entre les décisions de traitement du risque et l'applicabilité des mesures de l'Annexe A, avec justifications et état de mise en oeuvre.",
    "Weak SoAs are often generic; strong SoAs are traceable and specific.",
    "Les SoA faibles sont souvent génériques ; les SoA solides sont traçables et spécifiques.",
    [{ en: "Statement of Applicability", fr: "Déclaration d'applicabilité" }],
  ),
  single(
    "mx-007",
    "evidence",
    "medium",
    ["practitioner", "timed", "weak-areas"],
    "An auditor asks for evidence that access reviews occur quarterly. Which evidence would be strongest?",
    "Un auditeur demande la preuve que les revues d'accès sont réalisées trimestriellement. Quelle preuve serait la plus forte ?",
    [
      { id: "a", en: "A policy saying reviews should happen", fr: "Une politique indiquant que les revues doivent avoir lieu" },
      { id: "b", en: "A manager verbally confirming the process exists", fr: "Un manager confirmant oralement que le processus existe" },
      { id: "c", en: "Time-stamped review records showing users checked, decisions made, and follow-up actions tracked", fr: "Des enregistrements horodatés montrant les utilisateurs examinés, les décisions prises et le suivi des actions" },
      { id: "d", en: "A slide deck from last year’s awareness session", fr: "Un support de présentation de la sensibilisation de l'année dernière" },
    ],
    "c",
    "Policies describe intent, but evidence of operation usually comes from records showing the activity happened and what decisions were made.",
    "Les politiques décrivent l'intention, mais la preuve de fonctionnement provient généralement d'enregistrements montrant que l'activité a eu lieu et quelles décisions ont été prises.",
    "In audits, operational records usually outweigh stated intent.",
    "En audit, les enregistrements de fonctionnement pèsent généralement plus que l'intention déclarée.",
    [{ en: "Audit evidence", fr: "Preuve d'audit" }],
  ),
  single(
    "mx-008",
    "nonconformity",
    "hard",
    ["practitioner", "timed", "weak-areas"],
    "The organization has no formal risk assessment methodology, no current risk register, and no traceable treatment decisions. Which classification is most likely?",
    "L'organisation n'a pas de méthodologie formelle d'analyse des risques, pas de registre des risques à jour et pas de décisions de traitement traçables. Quelle classification est la plus probable ?",
    [
      { id: "a", en: "Observation", fr: "Observation" },
      { id: "b", en: "Minor nonconformity", fr: "Non-conformité mineure" },
      { id: "c", en: "Major nonconformity", fr: "Non-conformité majeure" },
      { id: "d", en: "No finding if leadership is supportive", fr: "Pas d'écart si la direction est favorable" },
    ],
    "c",
    "This is systemic failure in a core certifiable requirement area, not an isolated weakness. That pattern is much closer to a major nonconformity.",
    "Il s'agit d'une défaillance systémique sur une exigence certifiable centrale, et non d'une faiblesse isolée. Ce schéma correspond beaucoup plus à une non-conformité majeure.",
    "Severity depends on systemic impact, not only on how dramatic the wording sounds.",
    "La gravité dépend de l'impact systémique, pas seulement du caractère spectaculaire du libellé.",
    [{ en: "Risk methodology and treatment", fr: "Méthodologie de risque et traitement" }],
  ),
  multi(
    "mx-009",
    "audit",
    "medium",
    ["practitioner", "timed", "weak-areas"],
    "Which actions are appropriate in a competent internal audit? Select all that apply.",
    "Quelles actions sont appropriées dans un audit interne compétent ? Sélectionnez toutes les réponses applicables.",
    [
      { id: "a", en: "Sampling records and tracing them to requirements", fr: "Échantillonner des enregistrements et les relier aux exigences" },
      { id: "b", en: "Only checking whether policy names look professional", fr: "Vérifier uniquement si les intitulés de politiques semblent professionnels" },
      { id: "c", en: "Interviewing process owners and testing consistency with records", fr: "Interroger les responsables de processus et tester la cohérence avec les enregistrements" },
      { id: "d", en: "Avoiding any finding that might make leadership uncomfortable", fr: "Éviter tout constat qui pourrait mettre la direction mal à l'aise" },
    ],
    ["a", "c"],
    "Internal audit should gather evidence, sample, interview, and test consistency. It is not branding review or comfort management.",
    "L'audit interne doit recueillir des preuves, échantillonner, interroger et tester la cohérence. Ce n'est ni une revue d'image ni une gestion du confort.",
    "Good internal audit supports improvement by being evidence-led and honest.",
    "Un bon audit interne soutient l'amélioration en étant piloté par la preuve et honnête.",
    [{ en: "Internal audit practice", fr: "Pratique de l'audit interne" }],
  ),
  single(
    "mx-010",
    "clauses",
    "medium",
    ["foundation", "timed", "weak-areas"],
    "Which clause is most directly linked to management review?",
    "Quelle clause est la plus directement liée à la revue de direction ?",
    [
      { id: "a", en: "Clause 4", fr: "Clause 4" },
      { id: "b", en: "Clause 7", fr: "Clause 7" },
      { id: "c", en: "Clause 9", fr: "Clause 9" },
      { id: "d", en: "Clause 10", fr: "Clause 10" },
    ],
    "c",
    "Management review is part of performance evaluation because leadership reviews whether the ISMS is suitable, adequate, and effective.",
    "La revue de direction relève de l'évaluation des performances car la direction examine si le SMSI est approprié, adéquat et efficace.",
    "Memorize clause numbers, but tie them back to purpose.",
    "Mémorisez les numéros de clause, mais reliez-les toujours à leur finalité.",
    [{ en: "Clause 9.3 Management review", fr: "Clause 9.3 Revue de direction" }],
  ),
  single(
    "mx-011",
    "implementation",
    "hard",
    ["practitioner", "timed"],
    "A startup wants certification fast and asks to write policies first, do risk assessment later, and worry about scope near the audit. What is the best response?",
    "Une startup veut se certifier rapidement et propose d'écrire les politiques d'abord, de faire l'analyse de risque plus tard et de réfléchir au périmètre à l'approche de l'audit. Quelle est la meilleure réponse ?",
    [
      { id: "a", en: "Agree, because policy volume is what auditors care about most", fr: "Accepter, car le volume de politiques est ce qui intéresse le plus les auditeurs" },
      { id: "b", en: "Push back and establish context, scope, and risk logic early so later policies and controls are coherent", fr: "S'opposer et établir tôt le contexte, le périmètre et la logique de risque afin que les politiques et mesures ultérieures soient cohérentes" },
      { id: "c", en: "Skip scope entirely if the company is small", fr: "Ignorer totalement le périmètre si l'entreprise est petite" },
      { id: "d", en: "Build the SoA first and use it as a substitute for scoping", fr: "Construire la SoA d'abord et l'utiliser comme substitut du périmètre" },
    ],
    "b",
    "Scope and risk logic shape the rest of the ISMS. Starting with paperwork detached from context usually creates brittle implementation and weak audit answers.",
    "Le périmètre et la logique de risque structurent le reste du SMSI. Commencer par une paperasse détachée du contexte produit souvent une mise en oeuvre fragile et de faibles réponses d'audit.",
    "Implementation sequence matters more than many teams admit.",
    "La séquence de mise en oeuvre compte plus que beaucoup d'équipes ne l'admettent.",
    [{ en: "Implementation journey", fr: "Parcours de mise en oeuvre" }],
  ),
  single(
    "mx-012",
    "terminology",
    "easy",
    ["bilingual", "foundation"],
    "Which French term best matches 'audit evidence'?",
    "Quel terme français correspond le mieux à 'audit evidence' ?",
    [
      { id: "a", en: "Preuve d'audit", fr: "Preuve d'audit" },
      { id: "b", en: "Mesure technique", fr: "Mesure technique" },
      { id: "c", en: "Plan d'affaires", fr: "Plan d'affaires" },
      { id: "d", en: "Contexte de l'organisme", fr: "Contexte de l'organisme" },
    ],
    "a",
    "'Preuve d'audit' is the direct professional term used in audit and compliance contexts.",
    "'Preuve d'audit' est le terme professionnel direct utilisé en contexte d'audit et de conformité.",
    "Bilingual readiness means using the right workplace term, not just a literal translation guess.",
    "La préparation bilingue suppose d'utiliser le bon terme de travail, pas seulement une traduction littérale approximative.",
    [{ en: "Bilingual terminology", fr: "Terminologie bilingue" }],
  ),
  single(
    "mx-013",
    "evidence",
    "hard",
    ["practitioner", "timed", "weak-areas"],
    "An incident response process exists, but sampled incidents from the past six months were handled in chat without tickets or documented escalation. What is the strongest auditor concern?",
    "Un processus de réponse à incident existe, mais les incidents échantillonnés des six derniers mois ont été traités dans un chat sans ticket ni escalade documentée. Quelle est la préoccupation d'audit la plus forte ?",
    [
      { id: "a", en: "The policy font is outdated", fr: "La police de la politique est dépassée" },
      { id: "b", en: "The process may exist on paper but is not being evidenced or followed consistently", fr: "Le processus peut exister sur le papier mais n'est ni démontré ni appliqué de manière cohérente" },
      { id: "c", en: "The company should switch frameworks immediately", fr: "L'entreprise devrait changer de référentiel immédiatement" },
      { id: "d", en: "There is no issue if the incidents were small", fr: "Il n'y a pas de problème si les incidents étaient mineurs" },
    ],
    "b",
    "Auditors care about operational effectiveness. If incidents bypass the defined workflow and leave weak records, the system may not be operating as claimed.",
    "Les auditeurs s'intéressent à l'efficacité opérationnelle. Si les incidents contournent le workflow défini et laissent peu de traces, le système peut ne pas fonctionner comme déclaré.",
    "Evidence gaps often expose process-effectiveness gaps.",
    "Les lacunes de preuve révèlent souvent des lacunes d'efficacité des processus.",
    [{ en: "Operational evidence", fr: "Preuve opérationnelle" }],
  ),
  multi(
    "mx-014",
    "soa",
    "hard",
    ["practitioner", "timed", "weak-areas"],
    "Which signs suggest a weak Statement of Applicability? Select all that apply.",
    "Quels signes suggèrent une Déclaration d'applicabilité faible ? Sélectionnez toutes les réponses applicables.",
    [
      { id: "a", en: "Generic justifications copied across many controls", fr: "Des justifications génériques copiées sur de nombreuses mesures" },
      { id: "b", en: "Implementation status linked to evidence owners", fr: "Un état de mise en oeuvre lié aux propriétaires de preuve" },
      { id: "c", en: "No traceable link between risks and applicability decisions", fr: "Aucun lien traçable entre les risques et les décisions d'applicabilité" },
      { id: "d", en: "Control exclusions explained with scope and context", fr: "Des exclusions de mesures expliquées par le périmètre et le contexte" },
    ],
    ["a", "c"],
    "Weak SoAs are generic and untraceable. Strong SoAs explain applicability, exclusions, and implementation status in a way that aligns with risk treatment and scope.",
    "Les SoA faibles sont génériques et non traçables. Les SoA solides expliquent l'applicabilité, les exclusions et l'état de mise en oeuvre de façon alignée sur le traitement du risque et le périmètre.",
    "A good SoA reads like a risk-based management artifact, not a copied table.",
    "Une bonne SoA se lit comme un artefact de management fondé sur le risque, pas comme un tableau copié.",
    [{ en: "SoA quality", fr: "Qualité de la SoA" }],
  ),
  single(
    "mx-015",
    "compare",
    "medium",
    ["foundation", "timed", "bilingual"],
    "What is ISO 19011 mainly used for in this context?",
    "À quoi sert principalement l'ISO 19011 dans ce contexte ?",
    [
      { id: "a", en: "Guidance on auditing management systems", fr: "Des lignes directrices pour l'audit des systèmes de management" },
      { id: "b", en: "A law governing personal data in Europe", fr: "Une loi régissant les données personnelles en Europe" },
      { id: "c", en: "The certifiable list of Annex A controls", fr: "La liste certifiable des mesures de l'Annexe A" },
      { id: "d", en: "A replacement for internal audits", fr: "Un remplacement des audits internes" },
    ],
    "a",
    "ISO 19011 provides auditing guidance. It helps structure audit planning, interviewing, sampling, and reporting approaches across management systems.",
    "L'ISO 19011 fournit des lignes directrices d'audit. Elle aide à structurer la planification, les entretiens, l'échantillonnage et le reporting des audits de systèmes de management.",
    "Separate auditing guidance from ISMS requirements and control guidance.",
    "Distinguez les lignes directrices d'audit des exigences du SMSI et des conseils sur les mesures.",
    [{ en: "ISO 19011", fr: "ISO 19011" }],
  ),
  single(
    "mx-016",
    "audit",
    "medium",
    ["practitioner", "timed"],
    "Which follow-up question would an external auditor most likely ask after seeing an undocumented offboarding case with lingering access?",
    "Quelle question de suivi un auditeur externe poserait-il le plus probablement après avoir vu un cas de départ non documenté avec des accès persistants ?",
    [
      { id: "a", en: "What color was the HR checklist?", fr: "De quelle couleur était la checklist RH ?" },
      { id: "b", en: "How widespread is this issue and what evidence shows it is isolated or systemic?", fr: "Quelle est l'étendue du problème et quelle preuve montre qu'il est isolé ou systémique ?" },
      { id: "c", en: "Can you rename the process before the audit closes?", fr: "Pouvez-vous renommer le processus avant la clôture de l'audit ?" },
      { id: "d", en: "Would you prefer a different standard instead?", fr: "Préféreriez-vous un autre référentiel ?" },
    ],
    "b",
    "Auditors often probe whether a finding is isolated or systemic because that influences risk perception and classification severity.",
    "Les auditeurs cherchent souvent à savoir si un constat est isolé ou systémique car cela influence la perception du risque et la gravité de la classification.",
    "Expect follow-up questions that test scale, recurrence, and control effectiveness.",
    "Attendez-vous à des questions de suivi testant l'ampleur, la récurrence et l'efficacité des mesures.",
    [{ en: "Audit follow-up", fr: "Suivi d'audit" }],
  ),
  single(
    "mx-017",
    "annex-a",
    "easy",
    ["foundation", "timed"],
    "How are Annex A controls grouped in the 2022 edition?",
    "Comment les mesures de l'Annexe A sont-elles regroupées dans l'édition 2022 ?",
    [
      { id: "a", en: "Legal, financial, technical, marketing", fr: "Juridique, financier, technique, marketing" },
      { id: "b", en: "Organizational, people, physical, technological", fr: "Organisationnel, humain, physique, technologique" },
      { id: "c", en: "Mandatory, optional, advisory, deprecated", fr: "Obligatoire, optionnel, indicatif, obsolète" },
      { id: "d", en: "Only technical and non-technical", fr: "Uniquement technique et non technique" },
    ],
    "b",
    "The 2022 structure groups controls into organizational, people, physical, and technological categories.",
    "La structure 2022 regroupe les mesures en catégories organisationnelles, humaines, physiques et technologiques.",
    "Know the categories, but do not treat them as implementation priorities by default.",
    "Connaissez les catégories, mais ne les traitez pas automatiquement comme des priorités de mise en oeuvre.",
    [{ en: "Annex A 2022 structure", fr: "Structure Annexe A 2022" }],
  ),
  tf(
    "mx-018",
    "risk",
    "medium",
    ["foundation", "practitioner", "timed", "weak-areas"],
    "Accepting a risk can still be a valid treatment decision if it is justified and approved according to the organization’s framework.",
    "Accepter un risque peut rester une décision de traitement valide si elle est justifiée et approuvée selon le cadre de l'organisation.",
    true,
    "Acceptance is one of the classic treatment options. The key issue is whether it is justified, approved, and consistent with the organization’s risk criteria.",
    "L'acceptation fait partie des options classiques de traitement. La question clé est de savoir si elle est justifiée, approuvée et cohérente avec les critères de risque de l'organisation.",
    "A risk-based system allows reasoned acceptance, not only mitigation.",
    "Un système fondé sur le risque permet une acceptation raisonnée, pas seulement la mitigation.",
    [{ en: "Risk treatment options", fr: "Options de traitement du risque" }],
  ),
  single(
    "mx-019",
    "clauses",
    "hard",
    ["practitioner", "timed", "weak-areas"],
    "A company has many controls but has not defined interested parties, scope boundaries, or internal/external issues. Which clause area is especially weak?",
    "Une entreprise a de nombreuses mesures mais n'a pas défini les parties intéressées, les limites du périmètre ni les enjeux internes/externes. Quelle zone de clause est particulièrement faible ?",
    [
      { id: "a", en: "Clause 4 Context of the organization", fr: "Clause 4 Contexte de l'organisation" },
      { id: "b", en: "Clause 7 Support", fr: "Clause 7 Support" },
      { id: "c", en: "Clause 8 Operation", fr: "Clause 8 Opérations" },
      { id: "d", en: "Clause 10 Improvement", fr: "Clause 10 Amélioration" },
    ],
    "a",
    "Interested parties, context, and scope are core Clause 4 foundations. Weakness there often distorts the whole ISMS design.",
    "Les parties intéressées, le contexte et le périmètre constituent les fondations de la clause 4. Une faiblesse à ce niveau déforme souvent toute la conception du SMSI.",
    "A flashy control set cannot compensate for a weak context definition.",
    "Un ensemble de mesures impressionnant ne compense pas une définition faible du contexte.",
    [{ en: "Clause 4", fr: "Clause 4" }],
  ),
  multi(
    "mx-020",
    "evidence",
    "medium",
    ["practitioner", "timed", "weak-areas"],
    "Which items would normally count as audit evidence? Select all that apply.",
    "Quels éléments compteraient normalement comme preuve d'audit ? Sélectionnez toutes les réponses applicables.",
    [
      { id: "a", en: "Approved policy versions", fr: "Versions approuvées des politiques" },
      { id: "b", en: "Access review reports", fr: "Rapports de revue des accès" },
      { id: "c", en: "An unsupported personal opinion that no incidents occur", fr: "Une opinion personnelle non étayée selon laquelle aucun incident ne se produit" },
      { id: "d", en: "Restore test records", fr: "Enregistrements des tests de restauration" },
    ],
    ["a", "b", "d"],
    "Policies, review records, and restore tests are all classic forms of evidence. Unsupported personal belief is not sufficient evidence.",
    "Les politiques, les enregistrements de revue et les tests de restauration sont des formes classiques de preuve. Une croyance personnelle non étayée ne suffit pas.",
    "Evidence should be inspectable, attributable, and relevant.",
    "La preuve doit être vérifiable, attribuable et pertinente.",
    [{ en: "Evidence categories", fr: "Catégories de preuve" }],
  ),
  single(
    "mx-021",
    "nonconformity",
    "medium",
    ["practitioner", "timed", "weak-areas"],
    "Training policy exists, but attendance records are missing for the sampled period. What is the most likely interpretation?",
    "La politique de formation existe, mais les feuilles de présence manquent pour la période échantillonnée. Quelle est l'interprétation la plus probable ?",
    [
      { id: "a", en: "The policy alone proves the control is fully effective", fr: "La politique seule prouve que la mesure est pleinement efficace" },
      { id: "b", en: "There may be a gap between defined process and retained evidence of operation", fr: "Il peut exister un écart entre le processus défini et la preuve conservée de son fonctionnement" },
      { id: "c", en: "This automatically proves a major nonconformity", fr: "Cela prouve automatiquement une non-conformité majeure" },
      { id: "d", en: "No finding is possible if awareness training was mentioned in a meeting", fr: "Aucun constat n'est possible si la sensibilisation a été évoquée en réunion" },
    ],
    "b",
    "A documented process without retained evidence often points to an effectiveness or evidence-retention gap. Severity depends on scale and context.",
    "Un processus documenté sans preuve conservée signale souvent une lacune d'efficacité ou de conservation de preuve. La gravité dépend de l'ampleur et du contexte.",
    "Avoid extreme conclusions too early; reason from evidence and system impact.",
    "Évitez les conclusions extrêmes trop tôt ; raisonnez à partir de la preuve et de l'impact système.",
    [{ en: "Nonconformity reasoning", fr: "Raisonnement de non-conformité" }],
  ),
  single(
    "mx-022",
    "implementation",
    "medium",
    ["practitioner", "timed"],
    "What is the best description of the relationship between internal audit and improvement?",
    "Quelle est la meilleure description de la relation entre audit interne et amélioration ?",
    [
      { id: "a", en: "Internal audit is only for assigning blame", fr: "L'audit interne sert uniquement à désigner des coupables" },
      { id: "b", en: "Internal audit helps test effectiveness, surface gaps, and feed corrective action and improvement", fr: "L'audit interne aide à tester l'efficacité, faire ressortir les écarts et alimenter les actions correctives et l'amélioration" },
      { id: "c", en: "Improvement happens before internal audit, so they are unrelated", fr: "L'amélioration a lieu avant l'audit interne, donc ils n'ont aucun lien" },
      { id: "d", en: "Internal audit replaces management review", fr: "L'audit interne remplace la revue de direction" },
    ],
    "b",
    "Internal audit is part of the feedback loop that informs improvement. It should reveal gaps, not merely perform ritual checking.",
    "L'audit interne fait partie de la boucle de retour qui alimente l'amélioration. Il doit révéler les écarts, pas seulement effectuer une vérification rituelle.",
    "Audit is valuable when it changes the quality of the system, not when it just produces a report.",
    "L'audit a de la valeur lorsqu'il améliore la qualité du système, pas lorsqu'il produit seulement un rapport.",
    [{ en: "Improvement loop", fr: "Boucle d'amélioration" }],
  ),
  single(
    "mx-023",
    "terminology",
    "easy",
    ["bilingual", "foundation"],
    "Which bilingual pair is correct?",
    "Quelle paire bilingue est correcte ?",
    [
      { id: "a", en: "Statement of Applicability / Déclaration d'applicabilité", fr: "Statement of Applicability / Déclaration d'applicabilité" },
      { id: "b", en: "Risk treatment / Périmètre du SMSI", fr: "Risk treatment / Périmètre du SMSI" },
      { id: "c", en: "Audit evidence / Politique RH", fr: "Audit evidence / Politique RH" },
      { id: "d", en: "Nonconformity / Contrôle budgétaire", fr: "Nonconformity / Contrôle budgétaire" },
    ],
    "a",
    "The correct bilingual pair is Statement of Applicability / Déclaration d'applicabilité.",
    "La paire bilingue correcte est Statement of Applicability / Déclaration d'applicabilité.",
    "Terminology precision matters in bilingual audit and project conversations.",
    "La précision terminologique compte dans les conversations bilingues d'audit et de projet.",
    [{ en: "Bilingual workplace phrasing", fr: "Phraséologie bilingue de travail" }],
  ),
  single(
    "mx-024",
    "soa",
    "hard",
    ["practitioner", "timed", "bilingual"],
    "Which answer best shows professional SoA wording?",
    "Quelle réponse illustre le mieux une rédaction professionnelle de la SoA ?",
    [
      { id: "a", en: "Applicable because security is important", fr: "Applicable parce que la sécurité est importante" },
      { id: "b", en: "Not applicable because we do not like this control", fr: "Non applicable parce que nous n'aimons pas cette mesure" },
      { id: "c", en: "Applicable for in-scope production systems due to credential abuse and privilege-escalation risk; implementation evidenced through quarterly access reviews and joiner-mover-leaver controls", fr: "Applicable pour les systèmes de production dans le périmètre en raison du risque d'abus d'identifiants et d'élévation de privilèges ; mise en oeuvre démontrée par les revues d'accès trimestrielles et les contrôles d'arrivée-mobilité-départ" },
      { id: "d", en: "Applicable because Annex A says so", fr: "Applicable parce que l'Annexe A le dit" },
    ],
    "c",
    "Strong SoA wording ties applicability to scope, risk, and implementation evidence. It avoids generic statements.",
    "Une rédaction solide de la SoA relie l'applicabilité au périmètre, au risque et aux preuves de mise en oeuvre. Elle évite les formulations génériques.",
    "Professional wording is specific, risk-linked, and evidence-aware.",
    "Une formulation professionnelle est spécifique, liée au risque et consciente des preuves.",
    [{ en: "SoA rationale quality", fr: "Qualité de la justification SoA" }],
  ),
];

export function getDefinition(mode: MockExamMode) {
  return mockExamDefinitions.find((definition) => definition.id === mode) ?? mockExamDefinitions[0];
}
